### ISSUE TITLE
relate results not in [0,1]

### ISSUE THREAD

**Issue by beaucronin** [priorknowledge/loom#54]
<pre>
import loom.tasks
with loom.tasks.query('iris') as server:
    r = server.relate(['class'])
    print r

starting query server
class
class,1.0
petal_length,0.47097118047803571
petal_width,-8.5729378724973575
sepal_length,0.21172497039795185
sepal_width,0.15577187257576036
</pre>

**Comment by fritzo** [comment]
The problem is in `normalize_mutual_information`, where we assume `entropy > 0` whereas for continuous models entropy may be any real number. 

One possible solution is to shift nich entropy by the student's t entropy of the hyperparameters: http://en.wikipedia.org/wiki/Student's_t-distribution
